apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-demo
  template:
    metadata:
      labels:
        app: app-demo
    spec:
      containers:
        - name: app
          env:
          - name: APP_ServiceUri
            value: http://host.minikube.internal:3000/
          image: app:latest
          imagePullPolicy: Never
          livenessProbe:
            httpGet:
              path: /health/live
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: app-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    app: app-demo
  ports:
    - port: 80
      protocol: TCP
